name: ds_blake2b
description: A dart implement of blake2b referenced from blacknet, allows 224
version: 1.0.0
homepage: https://github.com/uac-nhan-nguyen/blake2b

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  hex: ^0.2.0

dev_dependencies:
  test: ^1.16.8
